http:
  host: '0.0.0.0'
  port: 8080
  domain: localhost
  enable_monitor: true

cors:
  headers:
    - '*'
  origins:
    - '*'
  methods:
    - '*'

databases:
  redis:
    host: redis
    port: 6379
    username: ''
    password: ''
    csrf:
      db: 2
